const AWS_REGION = import.meta.env.VITE_AWS_REGION;

// Cognito
const AWS_COGNITO_DOMAIN = import.meta.env.VITE_AWS_COGNITO_DOMAIN;
const AWS_COGNITO_AUTHORITY_URL = import.meta.env.VITE_AWS_COGNITO_AUTHORITY_URL;
const AWS_COGNITO_CLIENT_ID = import.meta.env.VITE_AWS_COGNITO_CLIENT_ID;
const AWS_COGNITO_REDIRECT_URL = import.meta.env.VITE_AWS_COGNITO_REDIRECT_URL;
const AWS_COGNITO_USER_POOL_ID = import.meta.env.VITE_AWS_COGNITO_USER_POOL_ID;
const AWS_COGNITO_IDENTITY_POOL_ID = import.meta.env.VITE_AWS_COGNITO_IDENTITY_POOL_ID;

// S3
const AWS_BUCKET_NAME = import.meta.env.VITE_AWS_BUCKET_NAME;

export {
    AWS_REGION,
    AWS_COGNITO_DOMAIN,
    AWS_COGNITO_AUTHORITY_URL,
    AWS_COGNITO_CLIENT_ID,
    AWS_COGNITO_REDIRECT_URL,
    AWS_COGNITO_USER_POOL_ID,
    AWS_COGNITO_IDENTITY_POOL_ID,
    AWS_BUCKET_NAME,
};
