export const entityFormFields = [
  {
    name: "entity_type",
    label: "Entity Type",
    type: "select",
    placeholder: "Please select entity type",
    required: true,
    options: [
      { label: "Manager", value: "Manager" },
      { label: "Sponsor", value: "Sponsor" },
      { label: "Trust", value: "Trust" },
      { label: "Custodian", value: "Custodian" },
      { label: "RTA", value: "RTA" },
      { label: "Trustee", value: "Trustee" },
      { label: "Auditor", value: "Auditor" },
      { label: "Merchant Banker", value: "Merchant Banker" },
      { label: "Legal Advisor", value: "Legal Advisor" },
      { label: "Compliance Officer", value: "Compliance Officer" },
      { label: "Accountant", value: "Accountant" },
      { label: "Tax", value: "Tax" },
    ],
  },
  {
    name: "entity_name",
    label: "Entity Name",
    type: "text",
    placeholder: "Please enter entity name",
    required: true,
  },
  {
    name: "entity_email",
    label: "Email",
    type: "email",
    placeholder: "Please enter entity email",
    required: true,
  },
  {
    name: "entity_telephone",
    label: "Phone Number",
    type: "phone",
    placeholder: "Please enter entity phone number",
    required: true,
  },
  {
    name: "entity_address",
    label: "Address",
    type: "textarea",
    placeholder: "Please enter entity address",
    required: true,
  },
  {
    name: "entity_pan",
    label: "PAN Number",
    type: "text",
    placeholder: "Please enter entity PAN number",
    required: true,
  },
  {
    name: "entity_breaking",
    type: "hr",
    className: "",
  },
  {
    name: "entity_breaking",
    type: "heading",
    label: "Other Details",
    className: "",
  },
  {
    name: "entity_breaking",
    type: "subheading",
    label: "Please fill in the following details as applicable",
  },
  {
    name: "entity_registration_number",
    label: "Registration Number",
    type: "text",
    placeholder: "Please enter entity registration number",
    required: false,
  },
  {
    name: "entity_tan",
    label: "TAN Number",
    type: "text",
    placeholder: "Please enter entity TAN number",
    required: false,
  },
  {
    name: "entity_gst_number",
    label: "GST Number",
    type: "text",
    placeholder: "Please enter entity GST number",
    required: false,
  },
  {
    name: "entity_poc",
    label: "Point of Contact",
    type: "text",
    placeholder: "Please enter entity point of contact",
    required: false,
  },
  {
    name: "entity_poc_din",
    label: "Point of Contact DIN",
    type: "text",
    placeholder: "Please enter entity point of contact DIN",
    required: false,
  },
  {
    name: "entity_poc_pan",
    label: "Point of Contact PAN",
    type: "text",
    placeholder: "Please enter entity point of contact PAN",
    required: false,
  },
];
