export const PortfolioCompanieCreateFeilds = [
  {
    name: "startup_brand",
    label: "Brand Name",
    type: "text",
    required: true,
    placeholder: "Enter startup brand name",
  },
  {
    name: "sector",
    label: "Sector",
    type: "multiSelect",
    required: true,
    placeholder: "Select up to 2 sectors",
    max: 2,
    options: [
      { label: "SaaS", value: "SaaS" },
      { label: "AI", value: "AI" },
      { label: "Education", value: "Education" },
      { label: "Health", value: "Health" },
      { label: "Logistics", value: "Logistics" },
      { label: "Media", value: "Media" },
      { label: "Food", value: "Food" },
      { label: "B2C Commerce", value: "B2C Commerce" },
      { label: "Finance", value: "Finance" },
      { label: "Deep Tech", value: "Deep Tech" },
      { label: "B2B Commerce", value: "B2B Commerce" },
    ],
  },
  {
    name: "subSector",
    label: "Sub-Sector",
    type: "multiSelect",
    required: true,
    placeholder: "Select one sub-sector per chosen sector",
    max: 2, 
  },
  {
    name: "product_description",
    label: "Product Description",
    type: "textarea",
    required: true,
    placeholder: "Describe the product",
  },
  {
    name: "pan",
    label: "PAN",
    type: "text",
    required: true,
    placeholder: "Enter PAN number",
  },
  {
    name: "isin",
    label: "ISIN",
    type: "text",
    required: true,
    placeholder: "Enter ISIN",
  },
  {
    name: "fund_id",
    label: "Fund ID",
    type: "fund_select",
    required: true,
    placeholder: "Enter Fund ID",
  },
  {
    name: "amount_invested",
    label: "Amount Invested",
    type: "number",
    required: true,
    placeholder: "Enter amount invested",
  },
  {
    name: "funding_date",
    label: "Date of Funding",
    type: "date",
    required: true,
    placeholder: "Select funding date",
  },
  {
    name: "termsheet_sign_date",
    label: "Date of Signing Term Sheet",
    type: "date",
    required: true,
    placeholder: "Select termsheet sign date",
  },
  {
    name: "ec_sign_date",
    label: "Date of Signing EC",
    type: "date",
    required: true,
    placeholder: "Select EC sign date",
  },
  {
    name: "latest_valuation",
    label: "Latest Valuation",
    type: "number",
    required: true,
    placeholder: "Enter latest valuation",
  },
  {
    name: "valuation_date",
    label: "Valuation Date",
    type: "date",
    required: true,
    placeholder: "Select valuation date",
  },
  {
    name: "sha_document",
    label: "SHA Document",
    type: "file",
    placeholder: "Upload SHA Document",
    required: true,
    dropZoneConfig: {
      useFsAccessApi: false,
      accept: {
        "application/pdf": [".pdf"],
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": [
          ".xlsx",
        ],
      },
      maxFiles: 1,
      maxSize: 1024 * 1024 * 10,
      multiple: false,
    },
  },
];

export const founderFields = [
  {
    name: "name",
    label: "Name",
    type: "text",
    required: true,
    placeholder: "Enter founder's name",
  },
  {
    name: "email",
    label: "Email",
    type: "email",
    required: true,
    placeholder: "Enter founder's email",
  },
  {
    name: "role",
    label: "Role",
    type: "text",
    required: true,
    placeholder: "Enter founder's role",
  },
  {
    name: "LinkedIn",
    label: "LinkedIn Profile",
    type: "text",
    required: false,
    placeholder: "Enter LinkedIn profile URL",
  },
];
