export const taskFormFields = [
  {
    name: "description",
    label: "Title",
    type: "text",
    placeholder: "",
    required: true,
  },
  {
    name: "attachments",
    label: "Supporting Documents",
    description: "Add relevant task related documents if needed.",
    type: "file",
    placeholder: "",
    required: false,
    dropZoneConfig: {
      useFsAccessApi: false,
      accept: {
        "application/pdf": [".pdf"],
      },
      maxFiles: 5,
      maxSize: 1024 * 1024 * 4,
      multiple: true,
    },
  },
  {
    name: "document_type",
    label: "Document Category",
    type: "select",
    placeholder: "Please select a document category",
    required: true,
    options: [
      { label: "Contribution Agreement", value: "Contribution Agreement" },
      { label: "KYC", value: "KYC" },
      { label: "Notification", value: "Notification" },
      { label: "Report", value: "Report" },
      { label: "Others", value: "Others" },
    ],
  },
  {
    name: "category",
    label: "Category",
    type: "select",
    placeholder: "Please select a category",
    required: true,
    options: [
      { label: "SEBI", value: "SEBI" },
      { label: "RBI", value: "RBI" },
      { label: "IT/GST", value: "IT/GST" },
      { label: "LP", value: "LP" },
      { label: "Portfolio Company", value: "Portfolio Company" },
    ],
  },
  {
    name: "deadline",
    label: "Deadline",
    type: "date",
    placeholder: "",
    required: true,
    pastDisable: true,
    futureDisable: false,
  },
  {
    name: "repeat",
    placeholder: "Repeat Task",
    type: "checkbox",
    required: false,
  },
  {
    name: "recurrence",
    label: "Frequency",
    type: "select",
    required: true,
    className: "",
    options: [
      { label: "Weekly", value: "Weekly" },
      { label: "Monthly", value: "Monthly" },
      { label: "Quarterly", value: "Quarterly" },
      { label: "Yearly", value: "Yearly" },
    ],
  },
  {
    name: "predecessor_task",
    label: "Predecessor Task",
    type: "task_select",
    placeholder: "",
    required: false,
  },
  {
    name: "assignee_id",
    label: "Assign To",
    type: "user_select",
    required: true,
  },
  {
    name: "reviewer_id",
    label: "Reviewer",
    type: "user_select",
    placeholder: "",
    required: true,
  },
  {
    name: "approver_id",
    label: "Final Reviewer",
    type: "user_select",
    placeholder: "",
    required: true,
  },
];
